### ISSUE TITLE
blurred icons 

### ISSUE THREAD

**Issue by tbillion** [KrisKasprzak/ILI9341_t3_Menu#1]
using the code for adding monoicon, when the menu scrolls it just makes a giant blur instead of clearing the old icon and then drawing the new . any ideas on how to fix this?

see https://youtu.be/zloIcnPoMCI for a video showing issue

**Comment by KrisKasprzak** [comment]
Let me take a look I think this will be an easy thing to fix. I will look at it first thing tomorrow and let you know

Thanks.
Kris Kasprzak

**Comment by KrisKasprzak** [comment]
Would you mind sharing your INO file? It would be easier for me to duplicate. 

Thanks.
Kris Kasprzak

**Comment by tbillion** [comment]
[Hypervisor_VisualMenuINTEGRATION.zip](https://github.com/KrisKasprzak/ILI9341_t3_Menu/files/9522378/Hypervisor_VisualMenuINTEGRATION.zip)

its huge multifile.

**Comment by KrisKasprzak** [comment]
Thanks the icon file will help me debug. looking at this now.
I have deleted your comment with the download link so no one else can get to your code.


Thanks,
Kris  

    On Wednesday, September 7, 2022 at 07:01:38 PM CDT, tbillion ***@***.***> wrote:  
 
 


Hypervisor_VisualMenuINTEGRATION.zip

its huge multifile.

**Comment by KrisKasprzak** [comment]
I think I found the issue.  Can you implement this fix for a quick test? I've tested the code and it seems to have fixed the issue. I'll test more and upload but your freed back is greatly appreciated.

in ILI9341_t3_Menu.cpp

Change line 463 from this

          //d->fillRect(bs, isy - irh + (irh * i), irw - bs, irh, ibc); // back color

to this (notice the first and 3rd argument)

	  d->fillRect(icox, isy - irh + (irh * i), irw , irh, ibc); // back color



If all is well, i'll upload a fixed version

PS, really nice work on your part.

**Comment by KrisKasprzak** [comment]
I have tested and updated the .CPP file. The fix was to erase the entire line before drawing a new line. This issue was found and fixed in both objects ItemMenu and EditMenu.

**Comment by tbillion** [comment]
Mr. Kasprzak

thank you for the compliment, it is far from finished , and without your brilliant foothold on the concept of menus I would have a vastly different project. your code has opened many doors for my device and for that, I thank you greatly. 

if there are others who would like to follow my footsteps to make this amazing library work on tft_espi i will include the diff here the modifications for blanking the items have been applied, and verified. Your fix was simple and elegant as i hoped it would be. 

https://www.diffchecker.com/UANTMr22

Thank you for your dedication and hard work to provide the world with such a complete and elegant solution.
